Display a summary in the tree RIB
imairi/RIBsTreeMaker pull request #2
Opened 2023-09-05 07:34 UTC by idonuntius

## Description

* Add `--summary` option to the command.
* The `--summary` option is to retrieve `// SUMMARY: - ` from the Builder file and display it in the tree. However, if `// SUMMARY: -` is not found, it is not displayed in the tree.

## Usage
command:

```
swift run RIBsTreeMaker [path/to/iOSproject] --under Root --summary
```

output:

```
@startmindmap
<style>
mindmapDiagram {
  . * {
    BackGroundColor #FFF
    LineColor #192f60
    Shadowing 0.0
    RoundCorner 20
    LineThickness 2.0
  }
  .noView * {
    BackGroundColor #FFF
    LineColor #d20b52
    TextColor #d20b52
  }
}
</style>
* Root / Root
** LoggedOut / LoggedOut summary<<noView>>
*** TermsOfUse / TermsOfUse summary
**** FailedLoading / FailedLoading summary
*** Welcome / Welcome summary
**** SignInFailedDialog
**** ForgotPassword
***** SMSAuthentication
****** ResetPassword
** LoggedIn<<noView>>
@endmindmap
```

<img width="1292" alt="スクリーンショット 2023-09-05 16 33 21" src="https://github.com/imairi/RIBsTreeMaker/assets/10494192/45ccfcd8-9d18-4d82-be6f-a67bce47b8a0">

2023-09-13 02:41 UTC, imairi commented
👁️

2023-09-13 03:17 UTC, imairi requested changes
実装ありがとうございます！
あとで実際に動かしてみて何かあれば追記します。

2023-09-13 03:17 UTC, imairi commented on README.md
> +* **summary**: the tree will be displayed summary is retrieved `// SUMMARY: - RIB summary` from the Builder file.
The RIB's summary is displayed in the node. The summary is retrieved `// SUMMARY: - RIB summary` from the Builder file.

という表現でどうでしょうか。マインドマップのノードひとつひとつにその要約が表示されることを示したいです。

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Error.swift
> +            return "Failed to Retrieve summary"
Retrieve -> retrieve

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Summary.swift
> +//  File.swift
`Summary.swift`

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +                print("Cannot create summary. Check the target path.")
[Rainbow](https://github.com/onevcat/Rainbow) というライブラリを使ってエラーであることを視覚的に分かりやすくしたいです。
MainCommand の init あたりを参考にしてください。

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +                return nil
`nil` が返ってきた == エラーというのが分かりづらいかなと思いました。
エラーのときは throw するのはどうでしょうか。（呼び出し元で catch してエラーハンドリングする）

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +            summary = searchedSummary != nil ? " / \(searchedSummary!.value)" : ""
if の中に `searchedSummary` を入れると `searchedSummary != nil ?` ここの判定省略できたりしませんかね。

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let suffixAndExtensionOfBuilderFile = "Builder.swift"
`AndExtension` はどういう意味でしょうか。

2023-09-13 03:17 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +                let result = results[0]
```
guard let result = results.first else {
    continue
}
```
これでいけそうな気がしました。

2023-09-13 03:31 UTC, idonuntius commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let suffixAndExtensionOfBuilderFile = "Builder.swift"
拡張子（ `.swift` ）という意味で使用していました。
suffixが `Builder` 部分でExtensionが `.swift` 部分で、こちらの変数名にしたのですが、 `suffixOfBuilderFile` でも良いでしょうか？

2023-09-13 04:45 UTC, idonuntius commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +                return nil
呼び出し先でdo-catchし、カスタムErrorでthrowさせ、呼び出し元ではカスタムErrorを取得し、failureを返すようにしましたがいかがでしょうか？

2023-09-14 08:47 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let suffixAndExtensionOfBuilderFile = "Builder.swift"
個人的には、`suffixOfBuilderFile` こちらのほうが分かりやすいかなと思いました。

2023-09-14 10:21 UTC, imairi requested changes

2023-09-14 10:21 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> -        }
👍

2023-09-14 10:21 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +                return nil
良さそうです！ありがとうございます。

2023-09-14 10:21 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let regexPattern = "// SUMMARY: - .+"
` - ` これ要りますかね。
 `// SUMMARY: ログアウト状態の RIB を束ねるもの` こちらのほうがシンプルかなと思ったのですが。

2023-09-14 10:21 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +            for builder in builders {
現状はすべての Builder ファイルに対して検索していますが、実際に出力する RIB に対して検索するほうが効率よいかなと思いました。
具体的には、showRIBsTree() 内の 161 行目あたりで SUMMARY の取得をすればよいのかなと思いまして。

※ そもそも Edges を作る際も指定した RIB を起点に作ったほうが効率よいですが..

2023-09-14 10:46 UTC, idonuntius commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let regexPattern = "// SUMMARY: - .+"
よく調べずにMARKと同じ形がいいかなと思い `-` をつけたのですが、 　`MARK: -` は「ライン付きのセクション見出し」という意味だったんですね・・・。 `-` は無くす方向にしたいと思います 🙇 
https://blog.code-candy.com/xcode_comment_improvement/

2023-09-14 15:12 UTC, idonuntius commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +            for builder in builders {
始めに出力するRIBに絞って検索をかけるということでしょうか？

現状ですと全てのBuilderファイルのSummaryを取得してから対象のRIBのsummaryを取得する流れになっており、確かに効率が悪いなと思っています。
ですので始めに全てのBuilderファイルのSummaryを取得するのをやめ、161行あたりで対象のRIBのBuilderファイルpathをpaths(指定したディレクトリの全てのファイルpath)から取得。その取得したpathからSUMMARYを取得する方向でもいいのかなと思っていますがいかがでしょうか？

2023-09-22 09:35 UTC, imairi commented on Sources/RIBsTreeMaker/Commands/MainCommand.swift
> +        let regexPattern = "// SUMMARY: - .+"
そうです！ MARK: のときは `-` に意味があるんですよね。

2023-09-22 10:13 UTC, imairi approved these changes
👍 LGTM 👍

2023-09-22 10:13 UTC, merged