Output RIBsTree in Whimsical mind map format
imairi/RIBsTreeMaker pull request #3
Opened 2023-09-26 14:04 UTC by idonuntius

## Description

* Add `-- format` option to the command, and convert from `--format` value to FormatType and pass to MainCommand.
* Add `TreeMaker` protocol. Add `PlantUMLFormat` and `WhimsicalFormat` to conform to `TreeMaker`.
* The common processing for `PlantUMLFormat` and `WhimsicalFormat` , previously described in `MainCommand` , has been moved to `TreeMaker` , and the methods described in `MainCommand` that are used only with `PlantUMLFormat` have been moved to `PlantUMLFormat` .

## Usage

command:

```sh
swift run RIBsTreeMaker [path/to/iOSproject] --under Root --format whimsical --summary
```

output:

```
Root / root summary
- LoggedOut(NoView) / loggedOut summary
  - TermsOfUse
    - FailedLoading
  - Welcome
    -  SignInFailedDialog
    - ForgotPassword
      - SMSAuthentication
      - ResetPassword
- LoggedIn(NoView)
```

paste in whimsical:

<img width="1133" alt="スクリーンショット 2023-09-26 22 41 03" src="https://github.com/imairi/RIBsTreeMaker/assets/10494192/ad7ca303-da23-445c-ba66-2242b6cb0b78">

2023-10-03 01:09 UTC, imairi requested changes

2023-10-03 01:09 UTC, imairi commented on README.md
> +swift run RIBsTreeMaker [path/to/iOSproject] --under [RIB name] [--format [plantUML or whimsical (default: plantUML)]] [--summary]
Whimsical はサービスの名称で、ここでの出力は一般的な Markdown 形式だと思うので、Markdown という名称にするのはどうでしょうか。（コード内の記述も。）

2023-10-03 01:09 UTC, imairi commented on Sources/RIBsTreeMaker/TreeMaker/WhismicalFormatTreeMaker.swift
> +        }
String repeating というメソッドを使うともう少し簡略化できそうです。
https://developer.apple.com/documentation/swift/string/init(repeating:count:)-23xjt

```
if count > 2 {
    prefix += String(repeating: "  ", count: count - 2)
}
```

2023-10-03 01:09 UTC, imairi commented on Sources/RIBsTreeMaker/TreeMaker/WhismicalFormatTreeMaker.swift
> +        }
```
let count = max(0, Int(count) - 2)
prefix += String(repeating: "  ", count: count) + "- "
```

もしかしたらこういうのでもいけるかもしれません。

2023-10-03 01:17 UTC, idonuntius commented on README.md
> +swift run RIBsTreeMaker [path/to/iOSproject] --under [RIB name] [--format [plantUML or whimsical (default: plantUML)]] [--summary]
whimsicalは下記で

```
Root / root summary
- LoggedOut(NoView) / loggedOut summary
  - TermsOfUse
    - FailedLoading
  - Welcome
    -  SignInFailedDialog
    - ForgotPassword
      - SMSAuthentication
      - ResetPassword
- LoggedIn(NoView)
```

markdownのリストは下記で

```
- Root / root summary
  - LoggedOut(NoView) / loggedOut summary
    - TermsOfUse
      - FailedLoading
    - Welcome
      -  SignInFailedDialog
      - ForgotPassword
        - SMSAuthentication
        - ResetPassword
  - LoggedIn(NoView)
  ```

Whimsicalとmarkdownで `Root` の `-` とインデントが若干異なるのですが、markdownにした方が良いでしょうか？

2023-10-03 01:21 UTC, imairi commented on README.md
> +swift run RIBsTreeMaker [path/to/iOSproject] --under [RIB name] [--format [plantUML or whimsical (default: plantUML)]] [--summary]
最初はいらないんですね…ではこのままにしておきましょう。

2023-10-04 00:30 UTC, idonuntius commented on README.md
> +swift run RIBsTreeMaker [path/to/iOSproject] --under [RIB name] [--format [plantUML or whimsical (default: plantUML)]] [--summary]
承知しました！
若干独自フォーマットなんですよね・・・

2023-10-05 02:14 UTC, idonuntius commented on README.md
> +swift run RIBsTreeMaker [path/to/iOSproject] --under [RIB name] [--format [plantUML or whimsical (default: plantUML)]] [--summary]
@imairi 

markdownのリストをwhimsicalに貼り付けたらちゃんとマインドマップが表示されました。
Whimsicalのマインドマップをコピーした場合は下記の様になりました。
Markdownで大丈夫そうですので、whimsicalという命名はMarkdownに変更します。

```
Root / root summary
- LoggedOut(NoView) / loggedOut summary
  - TermsOfUse
    - FailedLoading
  - Welcome
    -  SignInFailedDialog
    - ForgotPassword
      - SMSAuthentication
      - ResetPassword
- LoggedIn(NoView)
```

2023-10-06 04:04 UTC, idonuntius commented
@imairi 
修正しましたので、お手隙の際にレビューお願いします 🙇

2023-10-06 10:07 UTC, imairi approved these changes
👍 LGTM 👍

2023-10-06 10:07 UTC, merged